/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DraggableTree: typeof import('./components/DragOverTree.vue')['default']
    DragOverTree: typeof import('./components/DragOverTree.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InfoPanel: typeof import('./components/InfoPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitPanel: typeof import('./components/SplitPanel.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}
